from reference_types import Doc, Vocab
from typing import TypedDict, NotRequired

class StringOperator(TypedDict, total=False):
    IN: list[str]
    NOT_IN: list[str]
    IS_SUPERSET: list[str]
    INTERSECTS: list[str]

NumberOperator = TypedDict('NumberOperator', {
    '==': float, '!=': float, '>=': float, '<=': float, '>': float, '<': float,
    'IN': list[int], 'NOT_IN': list[int],
}, total=False)

class DependencyNode(TypedDict):
    RIGHT_ID: str
    RIGHT_ATTRS: dict[str, str | bool | StringOperator | NumberOperator]
    LEFT_ID: NotRequired[str]
    REL_OP: NotRequired[str]

class DependencyMatcher:
    def __init__(self, vocab: Vocab, *, validate: bool = False) -> None: ...
    def add(self, key: str, patterns: list[list[DependencyNode]]) -> None: ...
    def __call__(self, doc: Doc) -> list[tuple[int, list[int]]]: ...

class Matcher:
    def __init__(self, vocab: Vocab, *, validate: bool = False) -> None: ...
    def add(self, key: str, patterns: list[list[dict[str, str | bool | StringOperator | NumberOperator]]]) -> None: ...
    def __call__(self, doc: Doc) -> list[tuple[int, int, int]]: ...

class PhraseMatcher:
    def __init__(self, vocab: Vocab, attr: str = "ORTH", validate: bool = False) -> None: ...
    def add(self, key: str, docs: list[Doc] | Doc) -> None: ...
    def remove(self, key: str) -> None: ...
    def __contains__(self, key: str) -> bool: ...
    def __len__(self) -> int: ...
    def __call__(self, doc: Doc) -> list[tuple[int, int, int]]: ...
