from typing import NotRequired, TypedDict

from reference_types import Doc
from spacy.matcher import NumberOperator, StringOperator

TokenPatternItem = dict[str, str | bool | StringOperator | NumberOperator]

class EntityRulerPattern(TypedDict):
    label: str
    pattern: str | list[TokenPatternItem]
    id: NotRequired[str]

class EntityRuler:
    # Match keys (hashes of `label` or `label + ent_id_sep + id`) of patterns added with an ID.
    _ent_ids: dict[int, tuple[str, str]]
    def __call__(self, doc: Doc) -> Doc: ...
    def __len__(self) -> int: ...
    def match(self, doc: Doc) -> list[tuple[int, int, int]]: ...
    @property
    def labels(self) -> tuple[str, ...]: ...
    @property
    def ent_ids(self) -> tuple[str, ...]: ...
    @property
    def patterns(self) -> list[EntityRulerPattern]: ...
    def add_patterns(self, patterns: list[EntityRulerPattern]) -> None: ...
    def remove(self, ent_id: str) -> None: ...
    def clear(self) -> None: ...
